services:

  phinder:
    build: ./
    container_name: phinder 
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    expose:
      - 9200
      - 9300
